const fs = require('fs');
const path = require('path');

const postsDir = path.join(__dirname, '../posts');
const outputFile = path.join(__dirname, '../src/blogPosts.js');

function parseFrontmatter(fileContent) {
  // Regex to split YAML frontmatter block from markdown body content
  const match = fileContent.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return { attributes: {}, body: fileContent };

  const yamlBlock = match[1];
  const body = match[2].trim();
  const attributes = {};

  yamlBlock.split(/\r?\n/).forEach(line => {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) return;
    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();

    // Parse array formatting (e.g. ["React", "JavaScript"]) or simple strings
    if (value.startsWith('[') && value.endsWith(']')) {
      try {
        const jsonVal = value.replace(/'/g, '"');
        value = JSON.parse(jsonVal);
      } catch (e) {
        value = value.slice(1, -1).split(',').map(s => s.trim().replace(/^["']|["']$/g, ''));
      }
    } else if (value.startsWith('"') && value.endsWith('"')) {
      value = value.slice(1, -1);
    } else if (value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    
    attributes[key] = value;
  });

  return { attributes, body };
}

function run() {
  console.log('Compiling markdown posts...');
  
  if (!fs.existsSync(postsDir)) {
    console.error(`Error: posts directory not found at ${postsDir}`);
    process.exit(1);
  }

  const files = fs.readdirSync(postsDir);
  const postsMap = {};

  files.forEach(file => {
    if (!file.endsWith('.md')) return;

    const filePath = path.join(postsDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const { attributes, body } = parseFrontmatter(content);

    const id = attributes.id;
    const lang = attributes.lang || 'en'; // default to English if lang is missing

    if (!id) {
      console.warn(`Warning: Missing 'id' attribute in ${file}. Skipping.`);
      return;
    }

    if (!postsMap[id]) {
      postsMap[id] = {
        id: id,
        date: attributes.date || '',
        stardate: attributes.stardate || '',
        author: attributes.author || '',
        readTime: attributes.readTime || '',
        wordCount: parseInt(attributes.wordCount) || 0,
        category: attributes.category || '',
        en: null,
        zh: null
      };
    }

    // Merge localized fields
    postsMap[id][lang] = {
      title: attributes.title || '',
      summary: attributes.summary || '',
      tags: attributes.tags || [],
      content: body
    };
  });

  // Convert map to array and sort by date descending (newest first)
  const postsList = Object.values(postsMap).sort((a, b) => {
    return b.date.localeCompare(a.date);
  });

  // Generate output file content
  const outputContent = `// Automatically generated by scripts/build-posts.js. Do not edit directly.\n\nexport const blogPosts = ${JSON.stringify(postsList, null, 2)};\n`;

  // Create parent directory if missing
  const outputDir = path.dirname(outputFile);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputFile, outputContent, 'utf-8');
  console.log(`Success! Compiled ${postsList.length} articles into ${outputFile}`);
}

run();
